## SPDX-FileCopyrightText: (C) 2025 Intel Corporation
## SPDX-License-Identifier: Apache-2.0
---
dir: "mocks/m_{{.PackageName | lower}}"
outpkg: "m_{{.PackageName | lower}}"
filename: "mock_{{.InterfaceName | lower}}.go"
mockname: "Mock{{.InterfaceName}}"
with-expecter: true
packages:
  github.com/open-edge-platform/infra-core/inventory/v2/pkg/client:
    interfaces:
      InventoryClient:
