---

# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# buf.gen.yaml
# docs: https://docs.buf.build/configuration/v1/buf-gen-yaml

version: v1

plugins:

  # go - https://pkg.go.dev/google.golang.org/protobuf
  - plugin: go
    out: pkg
    opt:
      - paths=source_relative

  # python - https://github.com/danielgtaylor/python-betterproto
  # NOTE: This module creates empty directories in the repo root when run.
  # Ignore these like git does. Not sure if this is a buf or compiler issue
  - plugin: python_betterproto
    out: python/infra_inventory/errors
    strategy: all

  # docs - https://github.com/pseudomuto/protoc-gen-doc
  - plugin: doc
    out: docs/api
    opt: markdown,errors.md
    strategy: all
