---

# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# buf.gen.yaml
# docs: https://docs.buf.build/configuration/v1/buf-gen-yaml

version: v1

plugins:

  # go - https://pkg.go.dev/google.golang.org/protobuf
  - plugin: go
    out: pkg/api
    opt:
      - paths=source_relative

  # go grpc - https://pkg.go.dev/google.golang.org/grpc
  - plugin: go-grpc
    out: pkg/api
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false

  # ent - https://github.com/ent/contrib/tree/master/entproto/cmd/protoc-gen-ent
  - plugin: ent
    out: internal/ent
    opt:
      - schemadir=internal/ent/schema

  - plugin: go-filters
    out: internal/store
    path: ["go", "run", "./cmd/protoc-gen-go-filters"]

  # python - https://github.com/danielgtaylor/python-betterproto
  # NOTE: This module creates empty directories in the repo root when run.
  # Ignore these like git does. Not sure if this is a buf or compiler issue
  - plugin: python_betterproto
    out: python/infra_inventory
    strategy: all

  # docs - https://github.com/pseudomuto/protoc-gen-doc
  - plugin: doc
    out: docs/api
    opt: markdown,inventory.md
    strategy: all

  - plugin: go-const
    out: pkg/api
    path: ["go", "run", "./cmd/protoc-gen-go-const"]
    opt:
      - paths=source_relative
