---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# Edge Infrastructure Manager API Schema
#

# This file documents the Edge Infrastructure Manager API.

openapi: "3.0.2"

info:
  title: Edge Infrastructure Manager
  version: 0.1.0-dev
  description: Edge Infrastructure Manager API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "{apiRoot}/edge-infra.orchestrator.apis/v1"
    variables:
      apiRoot:
        default: "http://edge-infra.example.intel.com"
        description: "Defines the Edge Infrastructure Manager API entry point"

paths:
  /regions:
    "$ref": "./paths/locations.yaml#/regions"
  /sites:
    "$ref": "./paths/locations.yaml#/sites"
  /sites/{siteID}:
    "$ref": "./paths/locations.yaml#/siteID"
  /regions/{regionID}:
    "$ref": "./paths/locations.yaml#/regionID"
  /locations:
    "$ref": "./paths/locations.yaml#/locations"

  /ous:
    "$ref": "./paths/ous.yaml#/ous"
  /ous/{ouID}:
    "$ref": "./paths/ous.yaml#/ouID"

  /compute:
    "$ref": "./paths/compute.yaml#/compute"
  /compute/hosts:
    "$ref": "./paths/compute.yaml#/hosts"
  /compute/hosts/summary:
    "$ref": "./paths/compute.yaml#/hostsSummary"
  /compute/hosts/register:
    "$ref": "./paths/compute.yaml#/register"
  /compute/hosts/{hostID}:
    "$ref": "./paths/compute.yaml#/hostID"
  /compute/hosts/{hostID}/register:
    "$ref": "./paths/compute.yaml#/hostRegister"
  /compute/hosts/{hostID}/onboard:
    "$ref": "./paths/compute.yaml#/onboard"
  /compute/hosts/{hostID}/invalidate:
    "$ref": "./paths/compute.yaml#/hostInvalidate"

  /schedules:
    "$ref": "./paths/schedule.yaml#/schedules"
  /schedules/single:
    "$ref": "./paths/schedule.yaml#/singleSchedules"
  /schedules/single/{singleScheduleID}:
    "$ref": "./paths/schedule.yaml#/singleScheduleID"
  /schedules/repeated:
    "$ref": "./paths/schedule.yaml#/repeatedSchedules"
  /schedules/repeated/{repeatedScheduleID}:
    "$ref": "./paths/schedule.yaml#/repeatedScheduleID"

  /OSResources:
    "$ref": "./paths/os.yaml#/OSResources"
  /OSResources/{OSResourceID}:
    "$ref": "./paths/os.yaml#/OSResourceID"

  /workloads:
    "$ref": "./paths/workload.yaml#/workloads"
  /workloads/{workloadID}:
    "$ref": "./paths/workload.yaml#/workloadId"
  /workloadMembers:
    "$ref": "./paths/workload.yaml#/workloadMembers"
  /workloadMembers/{workloadMemberID}:
    "$ref": "./paths/workload.yaml#/workloadMembersID"

  /instances:
    "$ref": "./paths/instance.yaml#/instances"
  /instances/{instanceID}:
    "$ref": "./paths/instance.yaml#/instanceId"
  /instances/{instanceID}/invalidate:
    "$ref": "./paths/instance.yaml#/instanceInvalidate"

  /telemetry/groups/logs:
    "$ref": "./paths/telemetry.yaml#/telemetryLogsGroups"
  /telemetry/groups/logs/{telemetryLogsGroupId}:
    "$ref": "./paths/telemetry.yaml#/telemetryLogsGroupId"
  /telemetry/groups/metrics:
    "$ref": "./paths/telemetry.yaml#/telemetryMetricsGroups"
  /telemetry/groups/metrics/{telemetryMetricsGroupId}:
    "$ref": "./paths/telemetry.yaml#/telemetryMetricsGroupId"
  /telemetry/profiles/logs:
    "$ref": "./paths/telemetry.yaml#/telemetryLogsProfiles"
  /telemetry/profiles/metrics:
    "$ref": "./paths/telemetry.yaml#/telemetryMetricsProfiles"
  /telemetry/profiles/logs/{telemetryLogsProfileId}:
    "$ref": "./paths/telemetry.yaml#/telemetryLogsProfileId"
  /telemetry/profiles/metrics/{telemetryMetricsProfileId}:
    "$ref": "./paths/telemetry.yaml#/telemetryMetricsProfileId"

  /providers:
    "$ref": "./paths/provider.yaml#/providers"
  /providers/{providerID}:
    "$ref": "./paths/provider.yaml#/providerId"

  /localAccounts:
    "$ref": "./paths/localaccounts.yaml#/localAccounts"
  /localAccounts/{localAccountID}:
    "$ref": "./paths/localaccounts.yaml#/localAccountID"

components:
  schemas:
    "$ref": "./schemas/_index.yaml"

  responses:
    "$ref": "./responses/_index.yaml"
